// Generated by CoffeeScript 1.7.1
var AngularConstantsCompiler, escape, pathlib;

escape = require('js-string-escape');

pathlib = require('path');

module.exports = AngularConstantsCompiler = (function() {
  AngularConstantsCompiler.prototype.brunchPlugin = true;

  AngularConstantsCompiler.prototype.type = 'template';

  AngularConstantsCompiler.prototype.extension = 'json';

  AngularConstantsCompiler.prototype._default_path_transform = function(path) {
    return path;
  };

  function AngularConstantsCompiler(config) {
    var _ref, _ref1;
    this.module = ((_ref = config.plugins) != null ? (_ref1 = _ref.angular_constants) != null ? _ref1.module : void 0 : void 0) || 'welkin';
  }

  AngularConstantsCompiler.prototype.compile = function(data, path, callback) {
    var constant_name;
    constant_name = pathlib.basename(path, '.json');
    return callback(null, "(function() {\n    var module;\n\n    try {\n        // Get current constants module\n        module = angular.module('" + this.module + "');\n    } catch (error) {\n        // Or create a new one\n        module = angular.module('" + this.module + "', []);\n    }\n\n    module.constant('" + constant_name + "', " + data + ");\n})();");
  };

  return AngularConstantsCompiler;

})();
